In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
dataset=pd.read_csv('/content/Social_Network_Ads.csv')
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values

In [ ]:
print(dataset.columns[[2,3]])
print(dataset.columns[4])

Index(['Age', 'EstimatedSalary'], dtype='object')
Purchased


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)


In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train=sc_x.fit_transform(x_train)
x_test=sc_x.transform(x_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(x_train,y_train)
print(model)
y_pred_dec=model.predict(x_test)
y_pred_dec=model.predict(x_test)
y_pred_dec
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred_dec))

DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[[63  5]
 [ 6 26]]
0.89


In [ ]:
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)
modellr.fit(x_train,y_train)
print(modellr)
y_pred_lr=model.predict(x_test)
y_pred_lr=model.predict(x_test)
y_pred_lr
from sklearn.metrics import confusion_matrix
cmlr=confusion_matrix(y_test,y_pred_lr)
print(cmlr)
from sklearn.metrics import accuracy_score
print('Logistic Regression',accuracy_score(y_test,y_pred_lr))

LogisticRegression(random_state=0)
[[63  5]
 [ 6 26]]
Logistic Regression 0.89


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion ='entropy',random_state=0)
RFmodel.fit(x_train,y_train)
print(modellr)
y_pred_rf=RFmodel.predict(x_test)

from sklearn.metrics import confusion_matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
print(cmrf)
from sklearn.metrics import accuracy_score
print('RandomForest',accuracy_score(y_test,y_pred_rf))

LogisticRegression(random_state=0)
[[64  4]
 [ 4 28]]
RandomForest 0.92


In [ ]:
from sklearn.svc import SVC
model=SVC(kernel='rbf',C=1.0,gamma='scale',random_state=0)

In [ ]:
from sklearn.svc import SVC
model=SVC(kernel='poly',degree=3)
model.fit(x_train,y_train)
print(model)

ModuleNotFoundError: No module named 'sklearn.svc'